Change centos8 to rocky8
inmanta/std pull request #321
Opened 2022-02-01 12:49 UTC by FloLey

# Description

* Short description here *

closes *Add ticket reference here*

# Merge procedure

Don't use the github built-in merge, but the process described [here](https://docs.internal.inmanta.com/topics/tasks/commiting_changes_modules.html)

```sh
git pull
git checkout master
git pull
git merge --squash issue/{issue-number}-{short description}
inmanta module commit -m "{Commit Message Here}" -r
git push
git push {tag} # push the tag as well
```

Then close the PR with a reference to the commit

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-02-01 13:23 UTC, arnaudsjs requested changes

2022-02-01 13:23 UTC, arnaudsjs commented on tests/conftest.py
> +@pytest.fixture(scope="function", params=glob.glob("dockerfiles/*"))
This code assumes that the current working directory is the root of the project. This is not necessarily always the case. It's better to express the path to the `dockerfiles` directory relative to this file. You can obtain the path to this file using `__file__`. For example: https://github.com/inmanta/std/blob/47d92f3adf95786af07b231643736f9fe4342f74/tests/conftest.py#L33

2022-02-01 13:23 UTC, arnaudsjs commented on tests/conftest.py
> +    docker_build_cmd.append(f"./dockerfiles/{docker_file_name}.Dockerfile")
This code builds on top of the assumption that all the dockerfile end with the `.Dockerfile` extensions. It would be good to add that check that verifies whether that constraint is satisfied and give a clear error message when it's not.

2022-02-01 15:45 UTC, FloLey commented on tests/conftest.py
> +@pytest.fixture(scope="function", params=glob.glob("dockerfiles/*"))
```
    params=glob.glob(
        os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + "/dockerfiles/*"
    ),
```
Is this an acceptable solution? I didn't find a more proper way to do it.

2022-02-01 15:47 UTC, FloLey commented on tests/conftest.py
> +    docker_build_cmd.append(f"./dockerfiles/{docker_file_name}.Dockerfile")
I changed it to:
` docker_build_cmd.append(f"./dockerfiles/{os.path.basename(docker_file)}")`
I think it is better?

2022-02-01 15:53 UTC, wouterdb approved these changes

2022-02-01 16:15 UTC, sanderr requested changes
Two nitpicks, looks good otherwise.

2022-02-01 16:15 UTC, sanderr commented on tests/conftest.py
> +        os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + "/dockerfiles/*"
```suggestion
        os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "dockerfiles", "*")
```
Best to always use `os.path.join` to build paths. Among other things it makes sure to take differences between OS' into account.

2022-02-02 07:01 UTC, arnaudsjs approved these changes

2022-02-02 08:39 UTC, closed without merging