[FIX] check that environment is None before casting to str
inmanta/std pull request #353
Opened 2022-06-01 13:56 UTC by Hugo-Inmanta

# Description

Check that environment is None before casting to str

#282 

# Merge procedure

Don't use the github built-in merge, but the process described [here](https://docs.internal.inmanta.com/topics/tasks/commiting_changes_modules.html)

```sh
git pull
git checkout master
git pull
git merge --squash issue/{issue-number}-{short description}
inmanta module commit -m "{Commit Message Here}" -r
git push
git push {tag} # push the tag as well
```

Then close the PR with a reference to the commit

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
~~- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [ ] Correct, in line with design
~~- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2022-06-02 11:08 UTC, arnaudsjs requested changes

2022-06-02 11:08 UTC, arnaudsjs commented on plugins/__init__.py
> +    env = Config.get("config", "environment", None)
Let's also add a test case that verifies that the exception is raise when the environment is not set.

2022-06-02 14:03 UTC, arnaudsjs requested changes

2022-06-02 14:03 UTC, arnaudsjs commented on tests/test_unknown.py
> +    with pytest.raises(Exception):
```suggestion
def test_unknown_environment(project):
    """
    Ensure that an exception is raised when the std::environment() plugin is called when no environment is configured.
    """
    with pytest.raises(Exception):
```

2022-06-03 07:32 UTC, arnaudsjs approved these changes

2022-06-03 13:57 UTC, Hugo-Inmanta commented
Merged into master with 18b7599f68494b251668462124573d5c35c16303.

2022-06-03 13:57 UTC, closed without merging