Draft: porting ip module to std
inmanta/std pull request #407
Opened 2023-01-09 15:51 UTC by jptrindade

# Description

The `ipaddress.ip_network` function needs the strict option set to `False` when used with addresses that have host bits set. 
```
>>> import ipaddress
>>> 
>>> cidr = "192.168.1.100/24"
>>> 
>>> ipaddress.ip_network(cidr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/usr/lib/python3.10/ipaddress.py", line 1507, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 192.168.1.100/24 has host bits set
>>>
>>> network = ipaddress.ip_network(cidr, strict=False)
>>> network.network_address
IPv4Address('192.168.1.0')
```
This IPV4Network does not same the original address that was used in the creation of the network. In the ip module we could do `network.ip` and get `192.168.1.100`. There is no equivalent function in the `IPV4Network` model.

When typechecking with `ipv4/6/any_network` it assumes that strict mode is on and as such will fail with IPs that have the host bits set.
 
The failing tests are happening because validation is failing of an `IPv4Address` and `IPvAnyAddress` with value `"5236"`.
`ipaddress.ip_address(5236)` works fine but `ipaddress.ip_address("5236")` does not work. Is this something we want to support?

closes #377 

# Merge procedure

Don't use the github built-in merge, but the process described [here](https://internal.inmanta.com/developer/tasks/commiting_changes_modules.html)

```sh
git pull
git checkout master
git pull
git merge --squash issue/{issue-number}-{short description}
inmanta module commit -m "{Commit Message Here}" -r
git push
git push {tag} # push the tag as well
```

Then close the PR with a reference to the commit

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-01-09 16:00 UTC, jptrindade commented
@bartv 

> Why do we need this? Do you have examples to reference? There are two options:
> 
> 1. We constrain the type to ip network
> 2. We calculate the network from the address and use that further
> 
> Option 2 we only need to do when there is a valid use case.

Is this talking about the strict mode? I'm in favor of having it always set to True. Having strict mode set to False could lead to some errors where we expect the network to have a certain (incorrect) value but it is instead another (correct) value. If we always do strict mode, we at least can diagnose what is happening a bit better. This change will break a lot of tests.

2023-01-09 16:06 UTC, bartv commented
> Is this talking about the strict mode? I'm in favor of having it always set to True. Having strict mode set to False could lead to some errors where we expect the network to have a certain (incorrect) value but it is instead another (correct) value. If we always do strict mode, we at least can diagnose what is happening a bit better. This change will break a lot of tests.

The type has to be correct. Period. The question is, do we only accept network addresses or any ip address? For that we need to understand why you see this error? Are the uses of the plugin with an IP?

Then we can decide, do we accept all of them? Or does the user have to first convert an ip into a network and then use the plugin.

2023-01-09 16:38 UTC, jptrindade commented
> > Is this talking about the strict mode? I'm in favor of having it always set to True. Having strict mode set to False could lead to some errors where we expect the network to have a certain (incorrect) value but it is instead another (correct) value. If we always do strict mode, we at least can diagnose what is happening a bit better. This change will break a lot of tests.
> 
> The type has to be correct. Period. The question is, do we only accept network addresses or any ip address? For that we need to understand why you see this error? Are the uses of the plugin with an IP?
> 
> Then we can decide, do we accept all of them? Or does the user have to first convert an ip into a network and then use the plugin.

I took a look at systemtenant to see how the ip module is being used. Most were already using `std::ipv4_network` addresses (`AbstractSubnet.allocated_ip_subnet` and `AbstractSubnet.ip_subnet`) when calling most of the `ip` functions. The last use case I saw was this happening once in the code:
`network_ip = ip::ipnet("{{self.ip_address}}/{{self.prefix}}", "network")` and then `ip_subnet="{{network_ip}}/{{self.prefix}}"` . So it is using the ip::ipnet function to convert an ip address to a network. I assume that this ip can have host bits set (strict mode would not work) otherwise we would not need to call the function and just do `ip_subnet="{{self.ip_address}}/{{self.prefix}}"`.

Do you want me to check other repos that use the ip module? Is there any repo in specific that uses it a lot?

2023-01-09 17:43 UTC, bartv commented on model/_init.cf
> +typedef ipv4_cidr as string matching std::is_valid_cidr(self) == true
These types should not be taken from the ip module. There are other types that represent the same data:

https://github.com/inmanta/std/blob/master/model/_init.cf#L102

2023-01-09 17:44 UTC, bartv commented on plugins/__init__.py
> +def cidr_to_network(cidr: "string") -> "string":
same comment here

2023-01-09 17:45 UTC, bartv commented on plugins/__init__.py
> +def concat(host: "std::hoststring", domain: "std::hoststring") -> "std::hoststring":
this can be replaced by a string formatter in the model so should go as well

2023-01-09 17:46 UTC, bartv commented on plugins/__init__.py
> +def net_to_nm(network_addr: "string") -> "string":
can be replaced by the ipnet plugin

2023-01-09 17:47 UTC, bartv commented on plugins/__init__.py
> +def is_valid_ip(addr: "string") -> "bool":
given the new types and the pydantic plugin support this plugin is no longer required

2023-01-09 17:47 UTC, bartv commented on plugins/__init__.py
> +    if "/" not in addr:
given the new types and the pydantic plugin support this plugin is no longer required

2023-01-09 17:47 UTC, bartv commented on plugins/__init__.py
> +def is_valid_cidr(addr: "string") -> "bool":
given the new types and the pydantic plugin support this plugin is no longer required

2023-01-09 17:47 UTC, bartv commented on plugins/__init__.py
> +def is_valid_cidr_v10(addr: "string") -> "bool":
given the new types and the pydantic plugin support this plugin is no longer required

2023-01-09 17:47 UTC, bartv commented on plugins/__init__.py
> +def is_valid_ip_v10(addr: "string") -> "bool":
given the new types and the pydantic plugin support this plugin is no longer required

2023-01-09 17:51 UTC, bartv commented on plugins/__init__.py
> +def is_valid_netmask(netmask: "string") -> "bool":
do we know if this is used anywhere? seems to be only used by the ip::netmask typedef. I would prefer to leave this out for now

2023-01-09 17:53 UTC, bartv requested changes
see the individual comments

2023-01-10 10:21 UTC, jptrindade commented on plugins/__init__.py
> +def is_valid_netmask(netmask: "string") -> "bool":
I don't know if this is used anywhere else. I removed it for now.

2023-01-10 10:25 UTC, jptrindade commented
> The failing tests are happening because validation is failing of an IPv4Address and IPvAnyAddress with value "5236".
> ipaddress.ip_address(5236) works fine but ipaddress.ip_address("5236") does not work. Is this something we want to support?

I moved the typing tests to the appropriate folder but did not include the `"5236"` test case. Is it common to create IPs like this? It is a bit awkward that the model does not support this IP as string but it does as int

2023-01-10 13:42 UTC, bartv requested changes

2023-01-10 13:42 UTC, bartv commented on tests/test_plugins.py
> +def test_network_in_model_invalid_cidr(project):
I think we should get rid of the tests that just verify if the data type checking of the plugins works correctly. The core has  more than enough of these tests.

2023-01-10 13:42 UTC, bartv commented on tests/test_plugins.py
> +def test_cidr_to_network_in_model_invalid_cidr(project):
same here

2023-01-10 13:42 UTC, bartv commented on tests/test_plugins.py
> +    assert_compilation_error(project, model, "Invalid value '16', expected Number")
same here

2023-01-10 13:42 UTC, bartv commented on tests/test_plugins.py
> +def test_ipindex_in_model_invalid_position(project):
same here

2023-01-10 13:42 UTC, bartv commented on plugins/__init__.py
> +        | std::print(ipnet("192.168.1.100/24", "prefixlen"))  -->  24
these examples will not work any more with the current typing

2023-01-10 13:42 UTC, bartv commented on plugins/__init__.py
> +def ipnet(addr: "std::ipv_any_network", what: "string") -> "string":
It is probably easier to expand this plugin into separate plugins because this makes the typing a bit more complex and currently there is also not default which would cause strange failures. This would also allow us to use better typing.

The transformation/plugins I would provide are:

- ipv_any_interface-> prefixlength (You can use ip_interface for that:
   ```
   In [14]: ipaddress.ip_interface("192.168.0.1/24").network.prefixlen
   Out[14]: 24

   In [15]: ipaddress.ip_interface("192.168.0.0/24").network.prefixlen
   Out[15]: 24
    ```

- ipv_any_interface -> netmask
- ipv_any_interface -> network address

2023-01-10 14:40 UTC, jptrindade commented on plugins/__init__.py
> +def ipnet(addr: "std::ipv_any_network", what: "string") -> "string":
Is something like this what you had in mind?

2023-01-13 10:45 UTC, bartv requested changes
Looks good. Some minor comments.

2023-01-13 10:45 UTC, bartv commented on tests/test_plugins.py
> +    assert project.get_plugin_function("cidr_to_prefixlen")(cidr) == prefixlen
Let's also simplify the test cases. It makes no sense to have this variables it only reduces readability.

```suggestion
    assert project.get_plugin_function("cidr_to_prefixlen")("192.168.1.100/24") == "24"
    
```

2023-01-13 10:45 UTC, bartv commented on tests/test_plugins.py
> +    cidr = "192.168.1.100/24"
I would like to also see a test with a network address for example "192.168.1.0/24"

2023-01-13 15:30 UTC, wouterdb requested changes

2023-01-13 15:30 UTC, wouterdb commented on CHANGELOG.md
> +- Ported ip plugin to std
```suggestion
- Ported ip plugins to std
```

2023-01-13 15:30 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_prefixlen(addr: "std::ipv_any_interface") -> "int":
```suggestion
def prefixlen(addr: "std::ipv_any_interface") -> "int":
```

I would not add the 'cidr_to', I don't think these is a lot of chance at confusion

2023-01-13 15:30 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_network_address(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
```suggestion
def network_address(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
```

2023-01-13 15:30 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
```suggestion
def netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
```

2023-01-13 15:30 UTC, wouterdb commented on plugins/__init__.py
> +def add(addr: "std::ipv_any_address", n: "number") -> "std::ipv_any_address":
```suggestion
def add_to_ip(addr: "std::ipv_any_address", n: "number") -> "std::ipv_any_address":
```

I would add some prefix, as this would produce unexpected results when used as `add(3,5)=="0.0.0.8"`

2023-01-13 15:30 UTC, wouterdb commented on tests/test_plugins.py
> +def assert_compilation_error(project, model, error_message):
https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions

2023-01-13 15:30 UTC, wouterdb commented on tests/test_plugins.py
> +def run_test(project, thetype, value, is_ok):
What is this for?

2023-01-13 16:18 UTC, jptrindade commented on tests/test_plugins.py
> +def run_test(project, thetype, value, is_ok):
Forgot to delete this when I removed a lot of tests

2023-01-13 16:32 UTC, jptrindade commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
There already is a plugin called `netmask` that receives an integer (that I assume is the prefixlen) and returns the netmask. Should I rename that plugin?

2023-01-13 16:45 UTC, jptrindade commented on tests/test_plugins.py
> +def assert_compilation_error(project, model, error_message):
This is also a relic of the removed tests

2023-01-16 12:15 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
@bartv wdyt?

2023-01-16 12:15 UTC, wouterdb commented on plugins/__init__.py
> +def add(addr: "std::ipv_any_address", n: "number") -> "std::ipv_any_address":
this is still exactly the same?

2023-01-16 12:30 UTC, bartv commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
I like some consistency to I think the proposed changes are useful. But then we need to rename the other one. Any suggestions there? (or can core do dynamic binding for plugins in the next release ;-) )

2023-01-16 12:35 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
name the other one `netmask_with_length` ?

2023-01-16 12:43 UTC, bartv commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
for the other one? that name does not really say what it does. maybe something like: "prefixlength_to_netmask" ?

2023-01-16 13:31 UTC, jptrindade commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
I think `prefixlength_to_netmask` is a good solution. I think the only problem is that we now have a `std::netmask` function that has a different functionality than `ip::netmask` and might cause some inconsistencies when we completely deprecate the ip module.

@wouterdb I resolved the conversations as I was doing the changes. I only noticed this error with the duplicate function name afterwards so I wanted to correct it before I commited the changes. In the future I will only resolve the conversations once I push the changes.

2023-01-16 13:57 UTC, wouterdb commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
@jptrindade I prefer to resolve the ones I created myself, so I can keep track of them too

2023-01-16 14:09 UTC, jptrindade commented on plugins/__init__.py
> +def cidr_to_netmask(addr: "std::ipv_any_interface") -> "std::ipv_any_address":
ok, I will stop resolving the conversations and start asking for re-review when the changes are implemented.

2023-01-16 14:19 UTC, wouterdb commented on tests/test_plugins.py
> +        ("192.168.5.3/16", 1, "192.168.0.1"),
This is weird, it should not work afaik.

2023-01-16 14:26 UTC, wouterdb requested changes

2023-01-16 14:26 UTC, wouterdb commented on plugins/__init__.py
> +    net = ipaddress.ip_network(addr, False)
```suggestion
    net = ipaddress.ip_network(addr)
```

The false is not required, as the type is "std::ipv_any_network" which is the inmanta equivalent of `ipaddress.ip_network`

2023-01-16 14:49 UTC, jptrindade commented on tests/test_plugins.py
> +        ("192.168.5.3/16", 1, "192.168.0.1"),
I see, I will rewrite this test to use the compiler and update the inputs

2023-01-17 08:22 UTC, wouterdb approved these changes

2023-01-18 09:41 UTC, bartv approved these changes

2023-01-18 09:51 UTC, merged