Port std to validation_type method from inmanta-core
inmanta/std pull request #463
Opened 2023-10-03 12:28 UTC by arnaudsjs

# Description

Port the std module to the `validation_type()` method of inmanta-core.

closes inmanta/inmanta-core#6540

# Self Check:

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Version number is bumped to dev version
- [x] Code is clear and sufficiently documented
- [x] Sufficient test cases (reproduces the bug/tests the requested feature)
- [x] Correct, in line with design
- [ ] ~~End user documentation is included or an issue is created for end-user documentation~~

2023-10-03 12:52 UTC, sanderr requested changes
We should also bump the minimal compiler version (for v1) and add a constraint on core (for v2). I think the best we can do is to use the iso6 version for this, though we'd still be breaking older OSS versions then. I don't immediately see a way around this.

2023-10-03 12:52 UTC, sanderr commented on plugins/__init__.py
> +    except pydantic.ValidationError | ValueError:
I don't think this is supported on Python 3.9. I've never seen it before in this context but I'm assuming it's the union operator that was introduced in 3.10/3.11 (I forget).
```suggestion
    except (pydantic.ValidationError, ValueError):
```

2023-10-03 12:57 UTC, sanderr commented on plugins/__init__.py
> +            fq_type_name, value, validation_parameters
Technically this plugin can be used outside of a typedef as well, so I think it might be (and I think in a typedef it is as well but I'm not as sure about that). Perhaps converting it is best, considering that pydantic v2 might make this check more strict (e.g. no coercion).

2023-10-03 12:58 UTC, bartv commented on plugins/__init__.py
> +            fq_type_name, value, validation_parameters
The main question is: what is the type of value in this method: `inmanta.validation_type.validate_type`

2023-10-03 13:38 UTC, sanderr commented on plugins/__init__.py
> +            fq_type_name, value, validation_parameters
It doesn't allow `DynamicProxy` but it could be relaxed if we wanted to. I think I'm in favor of keeping it though.

2023-10-03 13:40 UTC, bartv commented on plugins/__init__.py
> +            fq_type_name, value, validation_parameters
I am also in favor of keeping the definition as it is, but then this code needs to unwrap

2023-10-03 13:40 UTC, sanderr commented on plugins/__init__.py
> +            fq_type_name, value, validation_parameters
Agreed.

2023-10-03 14:05 UTC, sanderr requested changes

2023-10-03 14:05 UTC, sanderr commented on plugins/__init__.py
> +    except(pydantic.ValidationError, ValueError):
```suggestion
    except (pydantic.ValidationError, ValueError):
```

2023-10-03 14:05 UTC, sanderr commented on plugins/__init__.py
> +    unwrapped_value = DynamicProxy.unwrap(value)
I think `None` values will give trouble, I forgot about that part. See [here](https://github.com/inmanta/lsm/blob/a5bc802d9dd6916b6467a0ba54362d3f3c2d7eb9/plugins/__init__.py#L337C1-L337C1).

2023-10-04 06:41 UTC, arnaudsjs commented on plugins/__init__.py
> +    unwrapped_value = DynamicProxy.unwrap(value)
Normally this shouldn't be a problem. A NullableType will not call the plugin when the value is null. But I added the if statement anyway.

2023-10-04 07:52 UTC, sanderr approved these changes

2023-10-04 12:13 UTC, arnaudsjs commented
@sanderr I requested re-review because I implemented #464 in this PR.

2023-10-05 08:28 UTC, sanderr commented
> @sanderr I requested re-review because I implemented https://github.com/inmanta/std/issues/464 in this PR.

Great. My apologies for making it a separate ticket. I was under the impression that this was already merged. I even checked but I must have made a mistake somewhere.

2023-10-05 08:34 UTC, sanderr approved these changes

2023-10-05 08:34 UTC, sanderr commented on plugins/__init__.py
> +def _validate_type_legacy(
Just as a sanity check, do you agree this will work under all circumstances?
- it is compatible with pydantic v1
- pydantic v2 can not be installed alongside older versions of core so this method will never be called in a pydantic v2 context.
- all pydantic object references are fully qualified so they will not be evaluated unless the method is called.

=>

- old core, old pydantic -> legacy behavior
- old core, new pydantic -> NA
- new core, old pydantic -> new behavior: core ensures compatibility
- new core, new pydantic -> new new behavior

2023-10-05 08:52 UTC, arnaudsjs commented on plugins/__init__.py
> +def _validate_type_legacy(
Yes. I think the above-mentioned things are correct.

2023-10-05 09:23 UTC, merged