Make sure module tests run against python 3.11
inmanta/std pull request #473
Opened 2023-10-27 10:15 UTC by Hugo-Inmanta

# Description

Make sure module tests run against python 3.11

closes https://github.com/inmanta/irt/issues/1729

note: to add a changelog entry and bump the version number:
`inmanta module release --dev [--major|--minor|--patch] [--changelog-message "<your_changelog_message>"]`

# [Merge procedure](https://internal.inmanta.com/development/core/tasks/commiting-changes-modules.html)

1. merge using the merge button
2. tag and bump

```sh
git checkout master
git pull
inmanta module release
git push
git push {tag} # push the tag as well
```
3. Remove the branch

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-10-27 14:38 UTC, Hugo-Inmanta commented on dockerfiles/rocky8.Dockerfile
> +RUN yum install -y python$PYTHON_VERSION glibc-locale-source gcc python3.11-devel.i686
I'm not super confident about this part.
Installing  `gcc` and `python3.11-devel.i686` is only required when running with python311 but I didn't find an elegant way to install them conditionally on the python version.

2023-10-30 14:45 UTC, sanderr requested changes

2023-10-30 14:45 UTC, sanderr commented on dockerfiles/rocky8.Dockerfile
> +RUN yum install -y python$PYTHON_VERSION glibc-locale-source gcc python3.11-devel.i686
This is not ideal. Do you think we could use Python containers instead of RHEL ones?

2023-10-30 14:45 UTC, sanderr commented on dockerfiles/centos7.Dockerfile
Is this one still used? I would think not.

2023-10-31 07:44 UTC, Hugo-Inmanta commented on dockerfiles/centos7.Dockerfile
It is in there -> https://jenkins.inmanta.com/job/modules/job/std/job/iso4/

2023-10-31 09:08 UTC, sanderr commented on dockerfiles/centos7.Dockerfile
Ah, we should just delete that branch.

2023-11-03 15:42 UTC, Hugo-Inmanta commented
Opened a fresh PR there -> https://github.com/inmanta/std/pull/476

2023-11-03 15:42 UTC, closed without merging