Issue/1729 run std module tests against python311
inmanta/std pull request #476
Opened 2023-11-03 15:15 UTC by Hugo-Inmanta

# Description

Add support for python 3.11

closes https://github.com/inmanta/irt/issues/1729

note: to add a changelog entry and bump the version number:
`inmanta module release --dev [--major|--minor|--patch] [--changelog-message "<your_changelog_message>"]`

# [Merge procedure](https://internal.inmanta.com/development/core/tasks/commiting-changes-modules.html)

1. merge using the merge button
2. tag and bump

```sh
git checkout master
git pull
inmanta module release
git push
git push {tag} # push the tag as well
```
3. Remove the branch

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2023-11-06 09:02 UTC, sanderr requested changes

2023-11-06 09:02 UTC, sanderr commented on tests/conftest.py
> +    if sys.version_info.major == 3 and sys.version_info.minor >= 11:
I see a few issues with your approach here: you condition on `>= 11`, but then use `3.11` in the dependency name, so the `>` part doesn't really apply. Then, where you use the option, you always use it, regardless of Python version, it just happens to be empty otherwise. I would rename the env var `PYTHON_DEVEL_PACKAGES` or something to be more generic.

2023-11-06 09:02 UTC, sanderr commented on CHANGELOG.md
> +- Add support for python 3.11
This is very misleading: we already support Python 3.11, we just didn't run the nightly tests against it. This change entry should really focus on the testing, and more on that it now supports multiple Python versions rather than 3.11 specifically.

2023-11-06 17:33 UTC, Hugo-Inmanta commented on tests/conftest.py
> +    if sys.version_info.major == 3 and sys.version_info.minor >= 11:
> I see a few issues with your approach here: you condition on >= 11, but then use 3.11 in the dependency name, so the > part doesn't really apply

I see, this is likely to break / require attention anytime we move to a new python version. I don't see a satisfying way out of this apart from raising an explicit exception when using python >= 3.12 ? 

> Then, where you use the option, you always use it, regardless of Python version, it just happens to be empty otherwise

This is by design, pass the extra installation requirements for python 3.11 and an empty string otherwise. Is there a cleaner alternative ?

2023-11-06 17:45 UTC, Hugo-Inmanta commented on tests/conftest.py
> +        docker_build_cmd.append("PYTHON311_SPECIFIC_ARGS=gcc python3.11-devel.i686")
I'm really not comfortable either, I don't think I had a specific reason for picking this one. I tested with `python3.11-devel` and it seems to work fine as well.

2023-11-07 15:58 UTC, sanderr approved these changes

2023-11-07 15:59 UTC, sanderr requested changes
Missed one thing, adding a comment to the relevant thread.

2023-11-07 16:00 UTC, sanderr commented on tests/conftest.py
> +    if sys.version_info.major == 3 and sys.version_info.minor >= 11:
> I don't see a satisfying way out of this apart from raising an explicit exception when using python >= 3.12

Why not use `sys.version_info` to create the dependency name?

> This is by design, pass the extra installation requirements for python 3.11 and an empty string otherwise. Is there a cleaner alternative ?

No, just by naming it `PYTHON311_SOMETHING` you give the impression that it's only used with Python 3.11. Now that you've renamed it there is no issue anymore.

2023-11-07 16:46 UTC, sanderr approved these changes

2023-11-07 16:46 UTC, sanderr commented
I think it's good now but I'm adding @arnaudsjs because he's more experienced with this.

2023-11-08 06:58 UTC, arnaudsjs requested changes
I guess the intention is that this solution would work for both python3.9 (iso6) and python3.11 (iso7), but I don't think it will. The packages for python3.9 and python3.11 have a different naming schema:

* For python3.9 the packages are called: `python39` and `python39-devel`
* For python3.11: `python3.11` and `python3.11-devel`

As far as I can see, this implementation will not work for any of both python versions. Or am I missing something. Did you test this?

2023-11-08 07:00 UTC, arnaudsjs commented on tests/conftest.py
> +
Do you know why `gcc` and python3.11-devel` are required for python3.11 and not for python3.9. That doesn't make much sense to me.

2023-11-08 08:17 UTC, Hugo-Inmanta commented on tests/conftest.py
> +
Without these I get this error when running the tests locally:
```
> [8/8] RUN if [ -e "inmanta_plugins" ]; then     env/bin/pip install --only-binary asyncpg -r requirements.dev.txt -c requirements.freeze;     rm -rf ./dist;     env/bin/inmanta module build;     env/bin/pip install -c requirements.freeze ./dist/*.whl; else     env/bin/pip install --only-binary asyncpg -r requirements.txt -r requirements.dev.txt -c requirements.freeze; fi:
38.42
38.42   note: This error originates from a subprocess, and is likely not a problem with pip.
38.42   ERROR: Failed building wheel for netifaces
38.42   Building wheel for pyformance (pyproject.toml): started
38.58   Building wheel for pyformance (pyproject.toml): finished with status 'done'
38.58   Created wheel for pyformance: filename=pyformance-0.4-py3-none-any.whl size=32180 sha256=0edaae341085a1da44ca109df3891ca3a29bc799d84089f8c466e9b3dee695de
38.58   Stored in directory: /root/.cache/pip/wheels/07/81/58/74c951e3d8148229a78d2e3f50d3390aba93c8d58d5fadf055
38.58 Successfully built inmanta-dev-dependencies flake8-isort pytest-inmanta crontab pyformance
38.58 Failed to build netifaces
38.58 ERROR: Could not build wheels for netifaces, which is required to install pyproject.toml-based projects
```

2023-11-08 08:41 UTC, Hugo-Inmanta commented
> As far as I can see, this implementation will not work for any of both python versions. Or am I missing something. Did you test this?

This seems to work as is for both versions. Here's how I tested it:  
- Create a python 3.11 | 3.9 venv
- run `pip install -r requirements.dev.txt -r requirements.txt`
- `export INMANTA_TEST_INFRA_SETUP=true`
- `python -m pytest tests`

Test passes for both. 

Please note that the `$PYTHON_DEVEL_PACKAGES` argument is actually an empty string for python 3.9
Also I tried just now for python 3.11 it seems that both `yum install -y python311` and `yum install -y python3.11` work (with and without `.` in version number)

2023-11-08 09:42 UTC, arnaudsjs commented on tests/conftest.py
> +
I see. `netifaces` didn't publish any wheels for python3.11.

2023-11-08 09:43 UTC, arnaudsjs commented
> Also I tried just now for python 3.11 it seems that both `yum install -y python311` and `yum install -y python3.11` work (with and without `.` in version number)

Indeed. dnf/yum seems to alias it. That doesn't work for the `-devel` package, but we don't need it for python3.9

2023-11-08 09:49 UTC, arnaudsjs commented on tests/conftest.py
> +
Wouldn't it be more robust to always install `gcc` and the `-devel` package. With the current implementation the build will break if a dependency updates and there is no compiled version available for the new pacakge. On the other hand iso6 will go in maintenance mode soon, so it will not get much dependency updates anymore. Let's leave it as it is and see what happens.

2023-11-08 09:49 UTC, arnaudsjs approved these changes

2023-11-08 10:00 UTC, merged