Constrain core ISO7
inmanta/std pull request #539
Opened 2024-08-27 08:46 UTC by hlloreda

# Description

Add a constraint to Inmanta core for ISO7 through the `CI-install` target.

note: to add a changelog entry and bump the version number:
`inmanta module release --dev [--major|--minor|--patch] [--changelog-message "<your_changelog_message>"]`

# [Merge procedure](https://internal.inmanta.com/development/core/tasks/commiting-changes-modules.html)

1. merge using the merge button
2. Wait for tests to pass
3. Add the tag and push it back

```sh
git checkout master
git pull
inmanta module release
git push
git push {tag} # push the tag as well
```
4. Remove the branch

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [ ] Attached issue to pull request
- [ ] Changelog entry
- [ ] Version number is bumped to dev version
- [ ] Code is clear and sufficiently documented
- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Correct, in line with design
- [ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )

2024-08-27 14:14 UTC, arnaudsjs requested changes

2024-08-27 14:14 UTC, arnaudsjs commented on Makefile
> +	env/bin/pip install -U -r requirements.txt -r requirements.dev.txt -c documented_constraints.txt
The problem with this approach is that it only solves the problem for the std module and only for the iso7 branch, while the same problem can occur on other modules and also on other branches of the std module that will be created in the future. As such, I think we have include this logic into the Jenkins pipeline itself.

@sanderr Do you agree?

2024-08-27 14:40 UTC, sanderr commented on Makefile
> +	env/bin/pip install -U -r requirements.txt -r requirements.dev.txt -c documented_constraints.txt
Wholeheartedly

2024-08-29 13:01 UTC, hlloreda commented
Blocked on https://github.com/inmanta/irt/pull/2183

2024-09-02 08:09 UTC, arnaudsjs approved these changes

2024-09-02 08:12 UTC, merged